---
abstract: 'Interface to the Yahoo BOSS Search API'
author:
  - 'Fred Moyer <fred@slwifi.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Yahoo-BOSS
no_index:
  directory:
    - t
    - inc
requires:
  Any::URI::Escape: 0
  Data::UUID: 1.217
  JSON::XS: 2.32
  LWP::UserAgent: 0
  Moo: 1.001000
  Net::OAuth: 0.27
version: 1.01
