--- #YAML:1.0
name:               WebService-Yahoo-BOSS
version:            0.04
abstract:           Interface to the Yahoo BOSS API
author:
    - Fred Moyer <fred@slwifi.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:        0
    Any::URI::Escape:  0
    LWP::UserAgent:    0
    XML::LibXML:       1.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
